#starting
from time import process_time, sleep
import os
os.system('cls')
from random import randrange
print('A fun fact while we load. This project has 200+ lines of code!')
sleep(2)
current = ('')
points = int(0)
def cl():
    os.system('cls')
def clear():
    os.system('cls')
def start():
    print('Oceans Rising')
    print(current)
def en():
    c1 = input("Press 'enter' to continue: ")
def end():
    en()
    cl()
def load():
    cl()
    times = (randrange(2, 10))
    while times > 0:
        print('Adding data: / ')
        sleep(0.1)
        clear()
        print('Adding data: | ')
        sleep(0.1)
        clear()
        print('Adding data: \ ')
        sleep(0.1)
        clear()
        print('Adding data: - ')
        sleep(0.1)
        clear()
        times = (times - 1)
    if times == 0:
        print('Done')
        sleep(0.5)
        clear()
cl()
name = input('(this data will not be saved) Before we begin, Please enter your name: ')
cl()
print('Oceans Rising (quiz)')
print(current)
print('By Levi')
print('')
en()
cl()
print('Would you like to see the info? (This may spoil the quiz) (Y/n)')
yn = input('>>> ')
if var == ('Y'):
    print('Part 1: Info')
    print('')
    print('Topic: Oceans rising')
    print('')
    en()
    cl()
    sleep(0.5)
    print('Effects')
    sleep(0.5)
    print('')
    sleep(0.5)
    print('Stronger Storms')
    sleep(0.5)
    print('')
    sleep(0.5)
    print('Death to ocean life')
    sleep(0.5)
    print('')
    sleep(0.5)
    print('Death to fish because some fish eat coral and coral is dying')
    sleep(0.5)
    print('')
    sleep(0.5)
    print('Oceans rising (losing land) because of ice melting')
    sleep(0.5)
    print('')
    sleep(0.5)
    print('Flooding')
    sleep(0.5)
    print('')
    sleep(0.5)
    print('Harmed')
    sleep(0.5)
    print('')
    sleep(0.5)
    print('People who live by beaches and all of humanity (because oceans will rise and the earth will heat up because the ocean can only take in so much heat)')
    sleep(0.5)
    print('')
    sleep(0.5)
    print('Equity')
    sleep(0.5)
    print('It affects some people more unfairly in poverty because they don’t have air conditioning, and masks for smokey days. \n They also don’t have the ability to start helping a lot to stop climate change')
    sleep(0.000005)
    print('It also affects people on small islands because they will sink without any technology to help keep the island above the ocean.')
    sleep(0.5)
    print('')
    sleep(0.5)
    print('solutions')
    sleep(0.5)
    print('')
    sleep(0.5)
    print('A solution might be to use reusable energy, and not use as much plastic bottles, and to not heat and cool your house as much')
    end()
elif var == ('n'):
    print('skipping part 1: info!')
else:
    print('Please use a CAPITOL Y, and a lowercase n, thanks!')
#Finished part one
print('Part: 2 (Quiz)')
sleep(0.5)
print('')
sleep(0.5)
print('Topic: Oceans rising')
sleep(0.5)
print('')
sleep(0.5)
print('By Levi')
#start section 1
print('Part: 2 (Quiz)')
sleep(0.5)
print('')
sleep(0.5)
print('Topic: Oceans rising')
sleep(0.5)
print('')
sleep(0.5)
print('A What is not an effect of oceans rising?')
sleep(0.5)
print('')
sleep(0.5)
print('1 - Coastal land loss')
print('2 - Volcanic eruptions')
print('3 - Change in ocean temperature.')
print('4 - Stronger Storms ')
print('Please enter the number corresponding to the correct question:')
answer1 = input('>>> ')
if answer1 == ('2'):
    points = (points + 1)
    answer1 = ('correct')
load()
sleep(2)
clear()
print('Part: 2 (Quiz)')
sleep(0.5)
print('')
sleep(0.5)
print('Topic: Oceans rising')
sleep(0.5)
print('')
sleep(0.5)
print('B.  who is harmed from oceans rising?')
sleep(0.5)
print('')
sleep(0.5)
print('1 - Some islanders')
print('2 - All of humanity')
print('3 - 1, and 2')
print('4 - The people who live inside of this computer ')
print('Please enter the number corresponding to the correct question:')
answer2 = input('>>> ')
if answer2 == ('3'):
    points = (points + 1)
    answer2 = ('correct')
load()
sleep(2)
clear()
print('Part: 2 (Quiz)')
sleep(0.5)
print('')
sleep(0.5)
print('Topic: Oceans rising')
sleep(0.5)
print('')
sleep(0.5)
print('note: This is a 2 point question!')
sleep(0.5)
print('')
sleep(0.5)
print('C Who is least harmed by oceans rising?')
sleep(0.5)
print('')
sleep(0.5)
print('1 - People who live by beaches/on islands')
print('2 - People who live in a houseboat')
print('3 - People who live near the equator ')
print('4 - People who live in an air conditioned/heated house, protected from flooding, with not severe weather ')
print('Please enter the number corresponding to the correct answer:')
answer3 = input('>>> ')
if answer3 == ('4'):
    points = (points + 2)
    answer3 = ('correct')
load()
sleep(2)
clear()
print('Part: 2 (Quiz)')
sleep(0.5)
print('')
sleep(0.5)
print('Topic: Oceans rising')
sleep(0.5)
print('')
sleep(0.5)
print('D How can you help the earth?')
sleep(0.5)
print('')
sleep(0.5)
print('1 - By drinking only out of plastic bottles forever')
print("2 - By ignoring global warming and just vibin’ ")
print('3 - Donating to ocean rescue projects')
print('4 - Using reusable stuff')
print('5 - 1 & 2')
print('6 - 3 & 4')
print('7 - None of the above remotely help the earth in any way')
print('Please enter the number corresponding to the correct question:')
answer4 = input('>>> ')
if answer4 == ('6'):
    points = (points + 1)
    answer4 = ('correct')
skilllevel = str('error displaying message')
print(points)
po = str(points)
if po == ('5'):
    skilllevel = str('Master Dolphin (all correct)')
if po == ('4'):
    skilllevel = str('Yong dolphin (1 to 2 missed)')
if po == ('3'):
    skilllevel = str('whale (2 to 3 missed)')
if po == ('2'):
    skilllevel = str('Young wale, you have much to learn (3, 4 missed)')
if po == ('1'):
    skilllevel = str('Coral (You got 1 right)')
if po == ('0'):
    skilllevel = str('sand (0 right)')
load()
sleep(2)
clear()
print('Done with the quiz! Let\'s see how you did!')
print('-------------------------------------------------------------------')
sleep(randrange(1, 2))
print('|                                                                 |')
sleep(randrange(1, 2))
print('|                    You Finished the Quiz!!                      |')
sleep(randrange(1, 2))
print('|                   You are a:', skilllevel, '                                 |')
sleep(randrange(1, 2))
print('|                     You have', points, 'Points!                        |')
sleep(randrange(1, 2))
print('|                                                                 |')
sleep(randrange(1, 2))
print('|           Congrats,', name, '                                        |')
sleep(randrange(1, 2))
print('|                                                                 |')
sleep(randrange(1, 2))
print('|                                                                 |')
sleep(randrange(1, 2))
print('------------------------------------------------------------------')
